
-- Note: Assumes maps and modes tables already exist with map_id and mode_id
-- If you need to populate them, use:
-- INSERT INTO maps (map_name) VALUES ('Blackheart'), ('Colossus'), ('Cortex'), ('Hijacked'), ('Raid'), ('The Forge');
-- INSERT INTO modes (mode_name) VALUES ('Hardpoint'), ('Search and Destroy'), ('Gunfight'), ('Free For All'), ('Team Deathmatch'), ('Overload');

-- Denormalized match table -------------------------------------------------
CREATE TABLE match_master (
    entry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    by_who TEXT,
    match_timestamp TIMESTAMPTZ DEFAULT NOW(),
    map_id INT REFERENCES maps (map_id),
    mode_id INT REFERENCES modes (mode_id),
    guild_score INT,
    jsoc_score INT,
    guild_player1_level INT,
    guild_player1_name TEXT,
    guild_player1_obj_score INT,
    guild_player1_time INT,
    guild_player1_obj_kills INT,
    guild_player1_captures INT,
    guild_player2_level INT,
    guild_player2_name TEXT,
    guild_player2_obj_score INT,
    guild_player2_time INT,
    guild_player2_obj_kills INT,
    guild_player2_captures INT,
    guild_player3_level INT,
    guild_player3_name TEXT,
    guild_player3_obj_score INT,
    guild_player3_time INT,
    guild_player3_obj_kills INT,
    guild_player3_captures INT,
    guild_player4_level INT,
    guild_player4_name TEXT,
    guild_player4_obj_score INT,
    guild_player4_time INT,
    guild_player4_obj_kills INT,
    guild_player4_captures INT,
    jsoc_player1_level INT,
    jsoc_player1_name TEXT,
    jsoc_player1_obj_score INT,
    jsoc_player1_time INT,
    jsoc_player1_obj_kills INT,
    jsoc_player1_captures INT,
    jsoc_player2_level INT,
    jsoc_player2_name TEXT,
    jsoc_player2_obj_score INT,
    jsoc_player2_time INT,
    jsoc_player2_obj_kills INT,
    jsoc_player2_captures INT,
    jsoc_player3_level INT,
    jsoc_player3_name TEXT,
    jsoc_player3_obj_score INT,
    jsoc_player3_time INT,
    jsoc_player3_obj_kills INT,
    jsoc_player3_captures INT,
    jsoc_player4_level INT,
    jsoc_player4_name TEXT,
    jsoc_player4_obj_score INT,
    jsoc_player4_time INT,
    jsoc_player4_obj_kills INT,
    jsoc_player4_captures INT
);

-- Seed sample matches ------------------------------------------------------
-- Note: Replace the map_id and mode_id values below with actual IDs from your maps and modes tables
-- Example: If 'Raid' has map_id=1 and 'Hardpoint' has mode_id=1, use those values
-- 
-- INSERT INTO match_master (
--     by_who, match_timestamp, map_id, mode_id,
--     guild_score, jsoc_score,
--     guild_player1_level, guild_player1_name, guild_player1_obj_score, guild_player1_time, guild_player1_obj_kills, guild_player1_captures,
--     guild_player2_level, guild_player2_name, guild_player2_obj_score, guild_player2_time, guild_player2_obj_kills, guild_player2_captures,
--     guild_player3_level, guild_player3_name, guild_player3_obj_score, guild_player3_time, guild_player3_obj_kills, guild_player3_captures,
--     guild_player4_level, guild_player4_name, guild_player4_obj_score, guild_player4_time, guild_player4_obj_kills, guild_player4_captures,
--     jsoc_player1_level, jsoc_player1_name, jsoc_player1_obj_score, jsoc_player1_time, jsoc_player1_obj_kills, jsoc_player1_captures,
--     jsoc_player2_level, jsoc_player2_name, jsoc_player2_obj_score, jsoc_player2_time, jsoc_player2_obj_kills, jsoc_player2_captures,
--     jsoc_player3_level, jsoc_player3_name, jsoc_player3_obj_score, jsoc_player3_time, jsoc_player3_obj_kills, jsoc_player3_captures,
--     jsoc_player4_level, jsoc_player4_name, jsoc_player4_obj_score, jsoc_player4_time, jsoc_player4_obj_kills, jsoc_player4_captures
-- )
-- VALUES
--     (
--         'Mario', NOW() - INTERVAL '2 days', 
--         (SELECT map_id FROM maps WHERE map_name = 'Raid'),
--         (SELECT mode_id FROM modes WHERE mode_name = 'Hardpoint'),
--         250, 189,
--         45, 'Mario', 4800, 420, 16, 8,
--         42, 'Kai', 3950, 415, 12, 6,
--         47, 'Danny', 3600, 405, 11, 4,
--         43, 'Gio', 3300, 398, 9, 3,
--         44, 'Jozy', 4100, 410, 13, 5,
--         40, 'Alan', 3650, 402, 10, 4,
--         41, 'Guest1', 3250, 396, 8, 2,
--         38, 'Guest2', 3000, 390, 7, 1
--     );


