-- Dev-only schema + seed data for BO7 tracker experiments
-- Safe to run inside a Supabase project's SQL editor or `psql` against a dev DB.

-- Clean slate for iterative testing
DROP TABLE IF EXISTS match_master CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS game_modes CASCADE;
DROP TABLE IF EXISTS maps CASCADE;

-- Reference data -----------------------------------------------------------
CREATE TABLE players (
    gamer_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    gamertag TEXT NOT NULL UNIQUE
);

INSERT INTO players (name, gamertag)
VALUES
    ('Mario', 'Nooport'),
    ('Kai', 'MuffinMan'),
    ('Danny', 'Dflo'),
    ('Gio', 'Kobe'),
    ('Jozy', 'BaconEggCheese'),
    ('Alan', 'retro');

CREATE TABLE game_modes (
    mode_code TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

INSERT INTO game_modes (mode_code, label)
VALUES
    ('HP', 'Hardpoint'),
    ('SND', 'Search and Destroy'),
    ('GF', 'Gunfight'),
    ('FFA', 'Free For All'),
    ('TDM', 'Team Deathmatch'),
    ('OVR', 'Overload');

CREATE TABLE maps (
    map_code TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

INSERT INTO maps (map_code, label)
VALUES
    ('BLACKHEART', 'Blackheart'),
    ('COLOSSUS', 'Colossus'),
    ('CORTEX', 'Cortex'),
    ('HIJACKED', 'Hijacked'),
    ('RAID', 'Raid'),
    ('FORGE', 'The Forge');

-- Denormalized match table -------------------------------------------------
CREATE TABLE match_master (
    entry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    by_who TEXT,
    match_timestamp TIMESTAMPTZ DEFAULT NOW(),
    map TEXT REFERENCES maps (map_code),
    mode TEXT REFERENCES game_modes (mode_code),
    guild_score INT,
    jsoc_score INT,
    guild_player1_level INT,
    guild_player1_name TEXT,
    guild_player1_obj_score INT,
    guild_player1_time INT,
    guild_player1_obj_kills INT,
    guild_player1_captures INT,
    guild_player2_level INT,
    guild_player2_name TEXT,
    guild_player2_obj_score INT,
    guild_player2_time INT,
    guild_player2_obj_kills INT,
    guild_player2_captures INT,
    guild_player3_level INT,
    guild_player3_name TEXT,
    guild_player3_obj_score INT,
    guild_player3_time INT,
    guild_player3_obj_kills INT,
    guild_player3_captures INT,
    guild_player4_level INT,
    guild_player4_name TEXT,
    guild_player4_obj_score INT,
    guild_player4_time INT,
    guild_player4_obj_kills INT,
    guild_player4_captures INT,
    jsoc_player1_level INT,
    jsoc_player1_name TEXT,
    jsoc_player1_obj_score INT,
    jsoc_player1_time INT,
    jsoc_player1_obj_kills INT,
    jsoc_player1_captures INT,
    jsoc_player2_level INT,
    jsoc_player2_name TEXT,
    jsoc_player2_obj_score INT,
    jsoc_player2_time INT,
    jsoc_player2_obj_kills INT,
    jsoc_player2_captures INT,
    jsoc_player3_level INT,
    jsoc_player3_name TEXT,
    jsoc_player3_obj_score INT,
    jsoc_player3_time INT,
    jsoc_player3_obj_kills INT,
    jsoc_player3_captures INT,
    jsoc_player4_level INT,
    jsoc_player4_name TEXT,
    jsoc_player4_obj_score INT,
    jsoc_player4_time INT,
    jsoc_player4_obj_kills INT,
    jsoc_player4_captures INT
);

-- Seed sample matches ------------------------------------------------------
INSERT INTO match_master (
    by_who, match_timestamp, map, mode,
    guild_score, jsoc_score,
    guild_player1_level, guild_player1_name, guild_player1_obj_score, guild_player1_time, guild_player1_obj_kills, guild_player1_captures,
    guild_player2_level, guild_player2_name, guild_player2_obj_score, guild_player2_time, guild_player2_obj_kills, guild_player2_captures,
    guild_player3_level, guild_player3_name, guild_player3_obj_score, guild_player3_time, guild_player3_obj_kills, guild_player3_captures,
    guild_player4_level, guild_player4_name, guild_player4_obj_score, guild_player4_time, guild_player4_obj_kills, guild_player4_captures,
    jsoc_player1_level, jsoc_player1_name, jsoc_player1_obj_score, jsoc_player1_time, jsoc_player1_obj_kills, jsoc_player1_captures,
    jsoc_player2_level, jsoc_player2_name, jsoc_player2_obj_score, jsoc_player2_time, jsoc_player2_obj_kills, jsoc_player2_captures,
    jsoc_player3_level, jsoc_player3_name, jsoc_player3_obj_score, jsoc_player3_time, jsoc_player3_obj_kills, jsoc_player3_captures,
    jsoc_player4_level, jsoc_player4_name, jsoc_player4_obj_score, jsoc_player4_time, jsoc_player4_obj_kills, jsoc_player4_captures
)
VALUES
    (
        'Mario', NOW() - INTERVAL '2 days', 'RAID', 'HP',
        250, 189,
        45, 'Mario', 4800, 420, 16, 8,
        42, 'Kai', 3950, 415, 12, 6,
        47, 'Danny', 3600, 405, 11, 4,
        43, 'Gio', 3300, 398, 9, 3,
        44, 'Jozy', 4100, 410, 13, 5,
        40, 'Alan', 3650, 402, 10, 4,
        41, 'Guest1', 3250, 396, 8, 2,
        38, 'Guest2', 3000, 390, 7, 1
    ),
    (
        'Kai', NOW() - INTERVAL '1 days', 'CORTEX', 'SND',
        6, 4,
        44, 'Kai', 1200, 210, 9, 0,
        39, 'Alan', 900, 208, 6, 0,
        NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL,
        43, 'Mario', 1100, 209, 8, 0,
        42, 'Jozy', 1050, 211, 7, 0,
        NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL
    ),
    (
        'Danny', NOW() - INTERVAL '8 hours', 'BLACKHEART', 'GF',
        10, 8,
        46, 'Danny', 1500, 160, 12, 0,
        43, 'Gio', 1400, 158, 10, 0,
        NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL,
        45, 'Mario', 1350, 150, 9, 0,
        42, 'Kai', 1300, 151, 8, 0,
        NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL
    );


